// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message.proto
// Protobuf Java Version: 4.28.3

package message;

public final class MessageOuterClass {
  private MessageOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      MessageOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string demand = 1;</code>
     * @return The demand.
     */
    java.lang.String getDemand();
    /**
     * <code>string demand = 1;</code>
     * @return The bytes for demand.
     */
    com.google.protobuf.ByteString
        getDemandBytes();

    /**
     * <code>string response = 2;</code>
     * @return The response.
     */
    java.lang.String getResponse();
    /**
     * <code>string response = 2;</code>
     * @return The bytes for response.
     */
    com.google.protobuf.ByteString
        getResponseBytes();

    /**
     * <code>optional .subscriber.Subscriber subscriber = 3;</code>
     * @return Whether the subscriber field is set.
     */
    boolean hasSubscriber();
    /**
     * <code>optional .subscriber.Subscriber subscriber = 3;</code>
     * @return The subscriber.
     */
    subscriber.SubscriberOuterClass.Subscriber getSubscriber();
    /**
     * <code>optional .subscriber.Subscriber subscriber = 3;</code>
     */
    subscriber.SubscriberOuterClass.SubscriberOrBuilder getSubscriberOrBuilder();
  }
  /**
   * Protobuf type {@code message.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:message.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        Message.class.getName());
    }
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      demand_ = "";
      response_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.MessageOuterClass.internal_static_message_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.MessageOuterClass.internal_static_message_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.MessageOuterClass.Message.class, message.MessageOuterClass.Message.Builder.class);
    }

    private int bitField0_;
    public static final int DEMAND_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object demand_ = "";
    /**
     * <code>string demand = 1;</code>
     * @return The demand.
     */
    @java.lang.Override
    public java.lang.String getDemand() {
      java.lang.Object ref = demand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        demand_ = s;
        return s;
      }
    }
    /**
     * <code>string demand = 1;</code>
     * @return The bytes for demand.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDemandBytes() {
      java.lang.Object ref = demand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        demand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONSE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object response_ = "";
    /**
     * <code>string response = 2;</code>
     * @return The response.
     */
    @java.lang.Override
    public java.lang.String getResponse() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        response_ = s;
        return s;
      }
    }
    /**
     * <code>string response = 2;</code>
     * @return The bytes for response.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResponseBytes() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        response_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBSCRIBER_FIELD_NUMBER = 3;
    private subscriber.SubscriberOuterClass.Subscriber subscriber_;
    /**
     * <code>optional .subscriber.Subscriber subscriber = 3;</code>
     * @return Whether the subscriber field is set.
     */
    @java.lang.Override
    public boolean hasSubscriber() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .subscriber.Subscriber subscriber = 3;</code>
     * @return The subscriber.
     */
    @java.lang.Override
    public subscriber.SubscriberOuterClass.Subscriber getSubscriber() {
      return subscriber_ == null ? subscriber.SubscriberOuterClass.Subscriber.getDefaultInstance() : subscriber_;
    }
    /**
     * <code>optional .subscriber.Subscriber subscriber = 3;</code>
     */
    @java.lang.Override
    public subscriber.SubscriberOuterClass.SubscriberOrBuilder getSubscriberOrBuilder() {
      return subscriber_ == null ? subscriber.SubscriberOuterClass.Subscriber.getDefaultInstance() : subscriber_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(demand_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, demand_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(response_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, response_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(3, getSubscriber());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(demand_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, demand_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(response_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, response_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getSubscriber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof message.MessageOuterClass.Message)) {
        return super.equals(obj);
      }
      message.MessageOuterClass.Message other = (message.MessageOuterClass.Message) obj;

      if (!getDemand()
          .equals(other.getDemand())) return false;
      if (!getResponse()
          .equals(other.getResponse())) return false;
      if (hasSubscriber() != other.hasSubscriber()) return false;
      if (hasSubscriber()) {
        if (!getSubscriber()
            .equals(other.getSubscriber())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEMAND_FIELD_NUMBER;
      hash = (53 * hash) + getDemand().hashCode();
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getResponse().hashCode();
      if (hasSubscriber()) {
        hash = (37 * hash) + SUBSCRIBER_FIELD_NUMBER;
        hash = (53 * hash) + getSubscriber().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static message.MessageOuterClass.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.MessageOuterClass.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.MessageOuterClass.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.MessageOuterClass.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.MessageOuterClass.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.MessageOuterClass.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.MessageOuterClass.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static message.MessageOuterClass.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static message.MessageOuterClass.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static message.MessageOuterClass.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.MessageOuterClass.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static message.MessageOuterClass.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(message.MessageOuterClass.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.Message)
        message.MessageOuterClass.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return message.MessageOuterClass.internal_static_message_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return message.MessageOuterClass.internal_static_message_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                message.MessageOuterClass.Message.class, message.MessageOuterClass.Message.Builder.class);
      }

      // Construct using message.MessageOuterClass.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getSubscriberFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        demand_ = "";
        response_ = "";
        subscriber_ = null;
        if (subscriberBuilder_ != null) {
          subscriberBuilder_.dispose();
          subscriberBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return message.MessageOuterClass.internal_static_message_Message_descriptor;
      }

      @java.lang.Override
      public message.MessageOuterClass.Message getDefaultInstanceForType() {
        return message.MessageOuterClass.Message.getDefaultInstance();
      }

      @java.lang.Override
      public message.MessageOuterClass.Message build() {
        message.MessageOuterClass.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public message.MessageOuterClass.Message buildPartial() {
        message.MessageOuterClass.Message result = new message.MessageOuterClass.Message(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(message.MessageOuterClass.Message result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.demand_ = demand_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.response_ = response_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.subscriber_ = subscriberBuilder_ == null
              ? subscriber_
              : subscriberBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof message.MessageOuterClass.Message) {
          return mergeFrom((message.MessageOuterClass.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(message.MessageOuterClass.Message other) {
        if (other == message.MessageOuterClass.Message.getDefaultInstance()) return this;
        if (!other.getDemand().isEmpty()) {
          demand_ = other.demand_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getResponse().isEmpty()) {
          response_ = other.response_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasSubscriber()) {
          mergeSubscriber(other.getSubscriber());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                demand_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                response_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getSubscriberFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object demand_ = "";
      /**
       * <code>string demand = 1;</code>
       * @return The demand.
       */
      public java.lang.String getDemand() {
        java.lang.Object ref = demand_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          demand_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string demand = 1;</code>
       * @return The bytes for demand.
       */
      public com.google.protobuf.ByteString
          getDemandBytes() {
        java.lang.Object ref = demand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          demand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string demand = 1;</code>
       * @param value The demand to set.
       * @return This builder for chaining.
       */
      public Builder setDemand(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        demand_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string demand = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDemand() {
        demand_ = getDefaultInstance().getDemand();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string demand = 1;</code>
       * @param value The bytes for demand to set.
       * @return This builder for chaining.
       */
      public Builder setDemandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        demand_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object response_ = "";
      /**
       * <code>string response = 2;</code>
       * @return The response.
       */
      public java.lang.String getResponse() {
        java.lang.Object ref = response_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          response_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string response = 2;</code>
       * @return The bytes for response.
       */
      public com.google.protobuf.ByteString
          getResponseBytes() {
        java.lang.Object ref = response_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          response_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string response = 2;</code>
       * @param value The response to set.
       * @return This builder for chaining.
       */
      public Builder setResponse(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        response_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string response = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponse() {
        response_ = getDefaultInstance().getResponse();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string response = 2;</code>
       * @param value The bytes for response to set.
       * @return This builder for chaining.
       */
      public Builder setResponseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        response_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private subscriber.SubscriberOuterClass.Subscriber subscriber_;
      private com.google.protobuf.SingleFieldBuilder<
          subscriber.SubscriberOuterClass.Subscriber, subscriber.SubscriberOuterClass.Subscriber.Builder, subscriber.SubscriberOuterClass.SubscriberOrBuilder> subscriberBuilder_;
      /**
       * <code>optional .subscriber.Subscriber subscriber = 3;</code>
       * @return Whether the subscriber field is set.
       */
      public boolean hasSubscriber() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .subscriber.Subscriber subscriber = 3;</code>
       * @return The subscriber.
       */
      public subscriber.SubscriberOuterClass.Subscriber getSubscriber() {
        if (subscriberBuilder_ == null) {
          return subscriber_ == null ? subscriber.SubscriberOuterClass.Subscriber.getDefaultInstance() : subscriber_;
        } else {
          return subscriberBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .subscriber.Subscriber subscriber = 3;</code>
       */
      public Builder setSubscriber(subscriber.SubscriberOuterClass.Subscriber value) {
        if (subscriberBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          subscriber_ = value;
        } else {
          subscriberBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional .subscriber.Subscriber subscriber = 3;</code>
       */
      public Builder setSubscriber(
          subscriber.SubscriberOuterClass.Subscriber.Builder builderForValue) {
        if (subscriberBuilder_ == null) {
          subscriber_ = builderForValue.build();
        } else {
          subscriberBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional .subscriber.Subscriber subscriber = 3;</code>
       */
      public Builder mergeSubscriber(subscriber.SubscriberOuterClass.Subscriber value) {
        if (subscriberBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            subscriber_ != null &&
            subscriber_ != subscriber.SubscriberOuterClass.Subscriber.getDefaultInstance()) {
            getSubscriberBuilder().mergeFrom(value);
          } else {
            subscriber_ = value;
          }
        } else {
          subscriberBuilder_.mergeFrom(value);
        }
        if (subscriber_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .subscriber.Subscriber subscriber = 3;</code>
       */
      public Builder clearSubscriber() {
        bitField0_ = (bitField0_ & ~0x00000004);
        subscriber_ = null;
        if (subscriberBuilder_ != null) {
          subscriberBuilder_.dispose();
          subscriberBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .subscriber.Subscriber subscriber = 3;</code>
       */
      public subscriber.SubscriberOuterClass.Subscriber.Builder getSubscriberBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getSubscriberFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .subscriber.Subscriber subscriber = 3;</code>
       */
      public subscriber.SubscriberOuterClass.SubscriberOrBuilder getSubscriberOrBuilder() {
        if (subscriberBuilder_ != null) {
          return subscriberBuilder_.getMessageOrBuilder();
        } else {
          return subscriber_ == null ?
              subscriber.SubscriberOuterClass.Subscriber.getDefaultInstance() : subscriber_;
        }
      }
      /**
       * <code>optional .subscriber.Subscriber subscriber = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          subscriber.SubscriberOuterClass.Subscriber, subscriber.SubscriberOuterClass.Subscriber.Builder, subscriber.SubscriberOuterClass.SubscriberOrBuilder> 
          getSubscriberFieldBuilder() {
        if (subscriberBuilder_ == null) {
          subscriberBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              subscriber.SubscriberOuterClass.Subscriber, subscriber.SubscriberOuterClass.Subscriber.Builder, subscriber.SubscriberOuterClass.SubscriberOrBuilder>(
                  getSubscriber(),
                  getParentForChildren(),
                  isClean());
          subscriber_ = null;
        }
        return subscriberBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:message.Message)
    }

    // @@protoc_insertion_point(class_scope:message.Message)
    private static final message.MessageOuterClass.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new message.MessageOuterClass.Message();
    }

    public static message.MessageOuterClass.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public message.MessageOuterClass.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_message_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\007message\032\020subscriber.pro" +
      "to\"k\n\007Message\022\016\n\006demand\030\001 \001(\t\022\020\n\010respons" +
      "e\030\002 \001(\t\022/\n\nsubscriber\030\003 \001(\0132\026.subscriber" +
      ".SubscriberH\000\210\001\001B\r\n\013_subscriberb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          subscriber.SubscriberOuterClass.getDescriptor(),
        });
    internal_static_message_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_message_Message_descriptor,
        new java.lang.String[] { "Demand", "Response", "Subscriber", });
    descriptor.resolveAllFeaturesImmutable();
    subscriber.SubscriberOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
